[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "/opt/homebrew/bin/solc"
remappings = [
    "ds-test/=lib/forge-std/lib/ds-test/src/",
    "@openzeppelin/=lib/openzeppelin-contracts/",
    "@chainlink/=lib/chainlink/"
]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
